#!/usr/bin/env python3
"""Keep the cloud-config payload identical to the standalone startup script."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys


PROJECT = Path(__file__).resolve().parents[1]
DESTINATION = PROJECT / "cloud-init/3xi.yaml"


PROVIDERS = {
    "stackscript.sh": """# <UDF name="THREEXI_REF" label="Git revision" default="main" />
# <UDF name="THREEXI_DOMAIN" label="Optional TLS domain (empty = local certificate)" default="" />
# <UDF name="THREEXI_ACME_EMAIL" label="Optional Let's Encrypt email" default="" />
# <UDF name="THREEXI_DNS_MODE" label="Resolver mode" default="public" oneof="public,preserve" />
# <UDF name="THREEXI_CLEAN_INSTALL" label="Delete previous installation without backup" default="0" oneof="0,1" />
""",
    "aws.sh": "# EC2 shell user-data / Lightsail launch script. Ubuntu or Debian images only.\n",
    "providers/gcp-startup.sh": "# GCE startup script; subsequent boots skip a completed installation.\n",
    "providers/vultr-startup.sh": "# Vultr boot script; Ubuntu or Debian images only.\n",
}


def render() -> str:
    script = (PROJECT / "scripts/bootstrap.sh").read_text()
    content = """#cloud-config
# Generated by scripts/render-cloud-init.py; edit scripts/bootstrap.sh instead.
# Ubuntu 24.04+ / Debian 12+, amd64 or arm64, with systemd and cloud-init.
# Defaults to main. Optional TLS: append --domain and your hostname in runcmd.
# Provider networking and SSH keys remain; xrm DNS profile is applied before APT.
write_files:
  - path: /var/lib/3xi-bootstrap/bootstrap.sh
    owner: root:root
    permissions: '0700'
    content: |
"""
    content += "".join("      " + line + "\n" for line in script.splitlines())
    content += """runcmd:
  - [bash, /var/lib/3xi-bootstrap/bootstrap.sh, --ref, main]
"""
    if len(content.encode("utf-8")) > 16 * 1024:
        raise ValueError("Cloud-config exceeds the EC2 16 KiB user-data limit")
    return content


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed YAML is stale")
    args = parser.parse_args()
    content = render()
    generated = {DESTINATION: content}
    bootstrap = (PROJECT / "scripts/bootstrap.sh").read_text()
    for relative, header in PROVIDERS.items():
        generated[PROJECT / relative] = bootstrap.replace("#!/usr/bin/env bash\n", "#!/usr/bin/env bash\n" + header, 1)
    if args.check:
        for path, expected in generated.items():
            if not path.is_file() or path.read_text() != expected:
                print("Generated startup file is stale: " + str(path.relative_to(PROJECT)), file=sys.stderr)
                return 1
        if not DESTINATION.is_file() or DESTINATION.read_text() != content:
            print("Run python3 scripts/render-cloud-init.py to refresh cloud-init/3xi.yaml", file=sys.stderr)
            return 1
        print(f"Cloud-config matches bootstrap.sh ({len(content.encode('utf-8'))} bytes).")
    else:
        for path, value in generated.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value)
            if path.suffix == ".sh":
                path.chmod(0o755)
        print("Updated cloud-init/3xi.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
